
parameters:

- name: useCache
  displayName: Use Cache?
  type: boolean
  default: true


steps:

- checkout: self
  fetchDepth: 0
  persistCredentials: true


- task: DownloadSecureFile@1
  name: devHubPrivateKey
  inputs:
      secureFile: privateKey_DevHub.key
  displayName: 'Get dev hub private key'


- ${{ if eq(parameters.useCache, true) }}:
  
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Configure npm cache


- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install @salesforce/cli@$(sfdxVersion) --global --loglevel verbose'
  displayName: Install sfdx with npm


- bash: |
        echo "Installing sfpowerkit plugin if no originally installed version is available ..."
        (sf plugins | grep -i "sfpowerkit") || (echo "y" | sf plugins install sfpowerkit@$(sfPowerkitVersion))
  
  displayName: 'Install sfdx plugins'


- bash: |
        echo "Tracing system variables..."
        echo "BUILD_REASON=$BUILD_REASON"
  
  displayName: 'Trace'

