
parameters:

- name: useCache
  displayName: Use Cache?
  type: boolean
  default: true


steps:

- checkout: self
  fetchDepth: 0
  persistCredentials: true


- task: DownloadSecureFile@1
  name: devHubPrivateKey
  inputs:
      secureFile: privateKey_DevHub.key
  displayName: 'Get dev hub private key'


- ${{ if eq(parameters.useCache, true) }}:
  
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Configure npm cache


- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install @salesforce/cli@$(sfdxVersion) --global --loglevel verbose'
  displayName: Install sfdx with npm
  retryCountOnTaskFailure: 1


- bash: |
        echo "Installing sfdmu plugin if no originally installed version is available ..."
        (sf plugins | grep -i "sfdmu") || (echo "y" | sf plugins install sfdmu@$(sfdmuVersion))
        
        echo "Installing sfpowerkit plugin if no originally installed version is available ..."
        (sf plugins | grep -i "sfpowerkit") || (echo "y" | sf plugins install sfpowerkit@$(sfPowerkitVersion))
  
  displayName: 'Install sfdx plugins'
  retryCountOnTaskFailure: 1


- bash: |
        
        export SF_DISABLE_SOURCE_MEMBER_POLLING="true"
        echo "##vso[task.setvariable variable=SF_DISABLE_SOURCE_MEMBER_POLLING]$SF_DISABLE_SOURCE_MEMBER_POLLING"
        
  displayName: 'Global Config'


- bash: |
        echo "Tracing system variables..."
        echo "BUILD_REASON=$BUILD_REASON"
  
  displayName: 'Trace'

