
parameters:

- name: pathToScan
  displayName: Directory with flows to scan
  type: string
  default: none


steps:

- script: |
      wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$(pmdVersion)/pmd-bin-$(pmdVersion).zip
      unzip pmd-bin-$(pmdVersion).zip -d pmd && cd pmd && cp -a pmd-bin-$(pmdVersion)/* . && rm -rf pmd-bin-$(pmdVersion)/
  displayName: 'PMD Downloading'
  
- task: Ant@1
  inputs:
    buildFile: 'pmd/build.xml'
    options: '-DpathToScan=${{parameters.pathToScan}}'
    targets: 'init pmd pmd-html-artifact pmd-html-publish'
    publishJUnitResults: false
    testResultsFiles: 'pmd/junit.xml'
    javaHomeOption: 'JDKVersion'
  displayName: 'PMD Analysis'
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/pmd/pmd-report-artifact-$(Build.BuildId).html'
    artifact: 'pmd-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML report to artifacts'
  
- task: publishhtmlreport@1
  inputs:
    htmlType: 'genericHTML'
    htmlPath: '$(System.DefaultWorkingDirectory)/pmd/pmd-report-publish-$(Build.BuildId).html'
  displayName: 'Publish HTML report to pipeline'


