/**
* Core package install handler class.
*/
global without sharing class FS_CoreInstallHandlerImpl implements CoreInstallHandler {
	
	
	global void beforeInstall(Map<String, Object> context) {
		
	}
	
	
	global void afterInstall(Map<String, Object> context) {
		
	}
	
	
	global void beforeUpgrade(Map<String, Object> context) {
		
	}
	
	
	global void afterUpgrade(Map<String, Object> context) {
		
	}
	
	
}