/**
* Field Service package install handler class.
*/
global class FS_FieldServiceInstallHandlerImpl implements FS_FieldServiceInstallHandler {
	
	
	global void beforeInstall(Map<String, Object> context) {
		
	}
	
	
	global void afterInstall(Map<String, Object> context) {
		
	}
	
	
	global void beforeUpgrade(Map<String, Object> context) {
		
	}
	
	
	global void afterUpgrade(Map<String, Object> context) {
		
	}
	
	
}