name: 'Push Field Service Package Version into Set of NAA Orgs by Schedule'


trigger: none

pr: none

#schedules:
#- cron: '0 6 * * *'
#  displayName: Nightly Field Service Package Version Bulk Push to NAA
#  branches:
#    include:
#    - dev-naa
#  always: false


parameters:

- name: versionToPushOrgAuthFiles
  displayName: Auth Files for Orgs to upgrade (comma-separated)
  type: string
  default: "authFile_devNAA,authFile_naaPool1,authFile_naaPool2,authFile_naaPool3"

- name: versionToPushExpression
  displayName: Package version expression to upgrade to
  type: string
  default: "X.* (Beta ?)"

- name: versionWhereCondition
  displayName: Where Condition for version to upgrade
  type: string
  default: "Branch IN ('dev-naa')"

- name: shouldInstallThirdParties
  displayName: Install Third Parties?
  type: boolean
  default: true

- name: autoInstallDependencies
  displayName: Auto Install Dependencies?
  type: boolean
  default: false

- name: installOnlyDependencies
  displayName: Install Only Dependencies?
  type: boolean
  default: false

- name: shouldRunAqaTests
  displayName: Run AQA Tests?
  type: boolean
  default: false

- name: shouldRunTestsBefore
  displayName: Run Tests (Before)?
  type: boolean
  default: true

- name: runTestsBeforeAsConcurrent
  displayName: Concurrent Tests (Before)?
  type: boolean
  default: true

- name: shouldRunTestsAfter
  displayName: Run Tests (After)?
  type: boolean
  default: true

- name: runTestsAfterAsConcurrent
  displayName: Concurrent Tests (After)?
  type: boolean
  default: true


variables:

- template: templates/variables.yml


stages:

- ${{ if not(eq(parameters.versionToPushOrgAuthFiles, 'none')) }}:
  
  - template: templates/bulkPushVersion.yml
    parameters:
      localizationDomain: "NAA"
      ${{ if eq(parameters.versionToPushOrgAuthFiles, 'default') }}:
        versionToPushOrgAuthFiles: $(push_FsNaa_toNaa)
      ${{ else }}:
        versionToPushOrgAuthFiles: ${{ parameters.versionToPushOrgAuthFiles }}
      versionToPushExpression: ${{ parameters.versionToPushExpression }}
      versionWhereCondition: ${{ parameters.versionWhereCondition }}
      autoInstallDependencies: ${{ parameters.autoInstallDependencies }}
      installOnlyDependencies: ${{ parameters.installOnlyDependencies }}
      shouldInstallThirdParties: ${{ parameters.shouldInstallThirdParties }}
      shouldRunTestsBefore: ${{ parameters.shouldRunTestsBefore }}
      runTestsBeforeAsConcurrent: ${{ parameters.runTestsBeforeAsConcurrent }}
      shouldRunTestsAfter: ${{ parameters.shouldRunTestsAfter }}
      runTestsAfterAsConcurrent: ${{ parameters.runTestsAfterAsConcurrent }}
      shouldRunAqaTests: ${{ parameters.shouldRunAqaTests }}


