name: 'Push Field Service Package Version into Set of Japan Orgs by Schedule'


trigger: none

pr: none

#schedules:
#- cron: '0 4 * * *'
#  displayName: Nightly Field Service Package Version Bulk Push to Japan
#  branches:
#    include:
#    - dev-jpn
#  always: false


parameters:

- name: versionToPushOrgAuthFiles
  displayName: Auth Files for Orgs to upgrade (comma-separated)
  type: string
  default: "authFile_devJpn,authFile_jpnPool1,authFile_jpnPool2,authFile_jpnPool3"

- name: versionToPushExpression
  displayName: Package version expression to upgrade to
  type: string
  default: "X.* (Beta ?)"

- name: versionWhereCondition
  displayName: Where Condition for version to upgrade
  type: string
  default: "Branch IN ('dev-jpn')"

- name: shouldRunTestsBefore
  displayName: Run Tests Before?
  type: boolean
  default: true

- name: shouldRunTestsAfter
  displayName: Run Tests After?
  type: boolean
  default: true


variables:

- template: templates/variables.yml


stages:

- ${{ if not(eq(parameters.versionToPushOrgAuthFiles, 'none')) }}:
  
  - template: templates/bulkPushVersion.yml
    parameters:
      localizationDomain: "Japan"
      ${{ if eq(parameters.versionToPushOrgAuthFiles, 'default') }}:
        versionToPushOrgAuthFiles: $(push_FsJpn_toJpn)
      ${{ else }}:
        versionToPushOrgAuthFiles: ${{ parameters.versionToPushOrgAuthFiles }}
      versionToPushExpression: ${{ parameters.versionToPushExpression }}
      versionWhereCondition: ${{ parameters.versionWhereCondition }}
      shouldRunTestsBefore: ${{ parameters.shouldRunTestsBefore }}
      shouldRunTestsAfter: ${{ parameters.shouldRunTestsAfter }}


