name: 'Push Field Service Package Version into Set of EMEA Orgs by Schedule'


trigger: none

pr: none

schedules:
- cron: '0 5 * * *'
  displayName: Nightly Field Service Package Version Bulk Push to EMEA
  branches:
    include:
    - dev-emea
  always: false


parameters:

- name: versionToPushOrgAuthFiles
  displayName: Auth Files for Orgs to upgrade (comma-separated)
  type: string
  default: "authFile_avgEMEA,authFile_devEMEA,authFile_emeaPool1,authFile_emeaPool2,authFile_emeaPool3"

- name: versionToPushExpression
  displayName: Package version expression to upgrade to
  type: string
  default: "X.* (Beta ?)"

- name: versionWhereCondition
  displayName: Where Condition for version to upgrade
  type: string
  default: "Branch IN ('dev-emea')"


variables:

- template: templates/variables.yml


stages:

- template: templates/bulkPushVersion.yml
  parameters:
    localizationDomain: "EMEA"
    versionToPushOrgAuthFiles: ${{ parameters.versionToPushOrgAuthFiles }}
    versionToPushExpression: ${{ parameters.versionToPushExpression }}
    versionWhereCondition: ${{ parameters.versionWhereCondition }}


