name: 'Create Field Service Package Version by Schedule'


trigger: none
    
pr: none

schedules:

- cron: '0 1 * * *'
  displayName: Nightly Field Service Global Package Version Build
  branches:
    include:
    - dev
  always: false

- cron: '0 2 * * *'
  displayName: Nightly Field Service Japan Package Version Build
  branches:
    include:
    - dev-jpn
  always: false

- cron: '0 3 * * *'
  displayName: Nightly Field Service EMEA Package Version Build
  branches:
    include:
    - dev-emea
  always: false

- cron: '0 4 * * *'
  displayName: Nightly Field Service NAA Package Version Build
  branches:
    include:
    - dev-naa
  always: false


parameters:

- name: envProfile
  displayName: Environment profile
  type: string
  default: default

- name: skipValidation
  displayName: Skip validation for package?
  type: boolean
  default: false

- name: branchMarker
  displayName: Branch marker for package
  type: string
  default: default

- name: createTag
  displayName: Create tag for version?
  type: boolean
  default: true

- name: shouldNotifySubscribers
  displayName: Notify Subscribers?
  type: boolean
  default: true


variables:
  
  - template: templates/variables.yml


stages:
    
    - stage: Upload
      
      displayName: Upload
      dependsOn: []
      
      jobs:
          
          - job: CreatePackageVersion
            
            displayName: 'Create Package Version'                         
            
            timeoutInMinutes: 0
            
            pool:
                vmImage: 'ubuntu-latest'
            
            steps:
            
            - template: templates/init.yml
            
            
            - template: templates/createVersion.yml
              parameters:
                envProfile: ${{ parameters.envProfile }}
                skipValidation: ${{ parameters.skipValidation }}
                ${{ if eq(parameters.branchMarker, 'default') }}:
                  branchMarker: ${{ variables['Build.SourceBranchName'] }}
                ${{ elseif not( eq(parameters.branchMarker, 'none') ) }}:
                  branchMarker: ${{ parameters.branchMarker }}
                createTag: ${{ parameters.createTag }}
                numberOfRetries: 1
              
              
            - ${{ if eq(parameters.shouldNotifySubscribers, true) }}:
              
              - template: templates/notifySubscribers.yml
                parameters:
                  ${{ if eq(variables['Build.SourceBranchName'], 'dev-jpn') }}:
                    subscribers: $(subs_pkgVersion_FsJpn)
                  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev-emea') }}:
                    subscribers: $(subs_pkgVersion_FsEMEA)
                  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev-naa') }}:
                    subscribers: $(subs_pkgVersion_FsNAA)
                  ${{ elseif eq(variables['Build.SourceBranchName'], 'dev') }}:
                    subscribers: $(subs_pkgVersion_FsGlobal_Dev)
                  ${{ elseif eq(variables['Build.SourceBranchName'], 'master') }}:
                    subscribers: $(subs_pkgVersion_FsGlobal_Master)
                  active: $(enableSubsPkgVersion)
              
            
